// AUTO-GENERATED by scripts/generate_menu_toolbar.py -- DO NOT EDIT
// Source of truth: config/menu_toolbar.yaml


/**
 * Handle editor-command menu actions.
 * Returns true if the action was handled, false otherwise.
 */
//============================================
export function handleEditorMenuAction(editor, actionId) {
  switch (actionId) {
    case "undo":
      editor.chain().focus().undo().run();
      return true;
    case "redo":
      editor.chain().focus().redo().run();
      return true;
    case "underline":
      editor.chain().focus().toggleUnderline().run();
      return true;
    case "subscript":
      editor.chain().focus().toggleSubscript().run();
      return true;
    case "superscript":
      editor.chain().focus().toggleSuperscript().run();
      return true;
    case "highlight":
      editor.chain().focus().toggleHighlight().run();
      return true;
    case "align_left":
      editor.chain().focus().setTextAlign("left").run();
      return true;
    case "align_center":
      editor.chain().focus().setTextAlign("center").run();
      return true;
    case "align_right":
      editor.chain().focus().setTextAlign("right").run();
      return true;
    case "align_justify":
      editor.chain().focus().setTextAlign("justify").run();
      return true;
    case "horizontal_rule":
      editor.chain().focus().setHorizontalRule().run();
      return true;
    case "insert_image": {
      const url = window.prompt("Enter image URL:");
      if (url) {
        editor.chain().focus().setImage({ src: url }).run();
      }
      return true;
    }
    case "insert_table":
      editor.chain().focus().insertTable({ rows: 3, cols: 3, withHeaderRow: true }).run();
      return true;
    case "code_block":
      editor.chain().focus().toggleCodeBlock().run();
      return true;
    default:
      return false;
  }
}
