// AUTO-GENERATED by scripts/generate_menu_toolbar.py -- DO NOT EDIT
// Source of truth: config/menu_toolbar.yaml


export const toolbarGroups = [
  {
    name: "History",
    buttons: [
      { label: "Undo", command: "undo", title: "Undo (Cmd+Z)" },
      { label: "Redo", command: "redo", title: "Redo (Cmd+Shift+Z)" },
    ],
  },
  {
    name: "Text",
    buttons: [
      { label: "B", command: "toggleBold", title: "Bold (Cmd+B)" },
      { label: "I", command: "toggleItalic", title: "Italic (Cmd+I)" },
      { label: "U", command: "toggleUnderline", title: "Underline (Cmd+U)" },
      { label: "S", command: "toggleStrike", title: "Strikethrough" },
      { label: "Sub", command: "toggleSubscript", title: "Subscript" },
      { label: "Sup", command: "toggleSuperscript", title: "Superscript" },
      { label: "Hi", command: "toggleHighlight", title: "Highlight" },
    ],
  },
  {
    name: "Heading",
    buttons: [
      { label: "P", command: "setParagraph", title: "Paragraph" },
      { label: "H1", command: "toggleHeading", args: { level: 1 }, title: "Heading 1" },
      { label: "H2", command: "toggleHeading", args: { level: 2 }, title: "Heading 2" },
      { label: "H3", command: "toggleHeading", args: { level: 3 }, title: "Heading 3" },
      { label: "H4", command: "toggleHeading", args: { level: 4 }, title: "Heading 4" },
      { label: "H5", command: "toggleHeading", args: { level: 5 }, title: "Heading 5" },
      { label: "H6", command: "toggleHeading", args: { level: 6 }, title: "Heading 6" },
    ],
  },
  {
    name: "Align",
    buttons: [
      { label: "Left", command: "setTextAlign", args: "left", title: "Align Left" },
      { label: "Center", command: "setTextAlign", args: "center", title: "Align Center" },
      { label: "Right", command: "setTextAlign", args: "right", title: "Align Right" },
      { label: "Justify", command: "setTextAlign", args: "justify", title: "Justify" },
    ],
  },
  {
    name: "Lists",
    buttons: [
      { label: "UL", command: "toggleBulletList", title: "Bullet List" },
      { label: "OL", command: "toggleOrderedList", title: "Ordered List" },
      { label: "BQ", command: "toggleBlockquote", title: "Blockquote" },
    ],
  },
  {
    name: "Code",
    buttons: [
      { label: "Code", command: "toggleCode", title: "Inline Code" },
      { label: "CB", command: "toggleCodeBlock", title: "Code Block" },
    ],
  },
  {
    name: "Insert",
    buttons: [
      { label: "Link", command: "setLink", title: "Insert Link" },
      { label: "HR", command: "setHorizontalRule", title: "Horizontal Rule" },
      { label: "Img", command: "insertImage", title: "Insert Image" },
      { label: "Table", command: "insertTable", title: "Insert Table (3x3)" },
    ],
  },
  {
    name: "Table",
    id: "ribbon-table-group",
    buttons: [
      { label: "+Row", command: "addRowAfter", title: "Add Row After" },
      { label: "-Row", command: "deleteRow", title: "Delete Row" },
      { label: "+Col", command: "addColumnAfter", title: "Add Column After" },
      { label: "-Col", command: "deleteColumn", title: "Delete Column" },
      { label: "DelTbl", command: "deleteTable", title: "Delete Table" },
    ],
    visibility: "in_table",
  },
];

export const activeStateChecks = [
  { label: "B", check: "bold" },
  { label: "I", check: "italic" },
  { label: "U", check: "underline" },
  { label: "S", check: "strike" },
  { label: "Sub", check: "subscript" },
  { label: "Sup", check: "superscript" },
  { label: "Hi", check: "highlight" },
  { label: "H1", check: "heading", args: { level: 1 } },
  { label: "H2", check: "heading", args: { level: 2 } },
  { label: "H3", check: "heading", args: { level: 3 } },
  { label: "H4", check: "heading", args: { level: 4 } },
  { label: "H5", check: "heading", args: { level: 5 } },
  { label: "H6", check: "heading", args: { level: 6 } },
  { label: "Left", checkAttr: { textAlign: "left" } },
  { label: "Center", checkAttr: { textAlign: "center" } },
  { label: "Right", checkAttr: { textAlign: "right" } },
  { label: "Justify", checkAttr: { textAlign: "justify" } },
  { label: "UL", check: "bulletList" },
  { label: "OL", check: "orderedList" },
  { label: "BQ", check: "blockquote" },
  { label: "Code", check: "code" },
  { label: "CB", check: "codeBlock" },
  { label: "Link", check: "link" },
];

export const specialHandlers = {
  "setLink": {
    type: "prompt_url",
    promptText: "Enter URL:",
    editorCommand: "setLink",
    argsKey: "href",
  },
  "insertImage": {
    type: "prompt_url",
    promptText: "Enter image URL:",
    editorCommand: "setImage",
    argsKey: "src",
  },
  "insertTable": {
    type: "insert_table",
  },
};

export const conditionalGroups = [
  { domId: "ribbon-table-group", condition: "in_table" },
];
